In [1]:
mylist = [1,2,3]

In [2]:
mylist

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
arr = np.array(mylist)

In [6]:
arr

array([1, 2, 3])

In [7]:
type(arr)

numpy.ndarray

In [8]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# Generate a array
np.arange(0,10)         # similar to range function of python

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# for all even numbers
np.arange(0,11,2)  

array([ 0,  2,  4,  6,  8, 10])

In [14]:
# to generate array with zeros
np.zeros(3)

array([0., 0., 0.])

In [15]:
# fora two-dimensional array
np.zeros((2,5))          # first number of tuple represents rows, second number represents columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
# arrays of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.linspace(0,5,10)            # linspace returns 1-d array with evenly spaced elements,
#first represents start point, second represents stop point, 
# third represents number of evenly spaced elements needed between start and stop points
# here stop point will be included as one of the element

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [22]:
# arange takes step size as third argument
# linspace takes number of elements needed as third argument

In [25]:
# Identity matrix -- no.of rows = no.of columns with 1s in diagonal elements and others as zero
np.eye(4)     # parameter is the number of rows or columns as both will be same

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# generate arrays with random numbers
np.random.rand(5)          # pass one parameter for one dimensional array

array([0.02173338, 0.48880285, 0.52749458, 0.22819834, 0.43092288])

In [27]:
# for 2-d array
np.random.rand(3,4)

array([[0.72966604, 0.37375389, 0.75073556, 0.15860735],
       [0.01156593, 0.18580987, 0.42838539, 0.83861079],
       [0.41002409, 0.58513311, 0.13549335, 0.0109638 ]])

In [29]:
# random samples from standard normal distribution
np.random.randn(2)
# This won't return numbers from 0 to 1
# This will return numbers from normal distribution centered from zero, 

array([-2.50431737, -0.16838351])

In [30]:
np.random.randn(4,4)

array([[ 0.93924028, -0.75559547,  0.02393142, -0.78264585],
       [ 0.38618948,  0.57042763,  1.68609145,  0.90195403],
       [ 0.59748312,  0.25774378,  0.38673492, -0.14727847],
       [ 1.55808519,  0.25737414,  0.18702868, -1.48300701]])

In [32]:
np.random.randint(1,100)# first parameter is low and second parameter is high, returns a integers between low and high
# return random integers between 1 and 100
# low is inclusive, high is exclusive

66

In [33]:
# For a particular number of random integers
np.random.randint(1,100,10)

array([61, 34, 98, 47, 80, 99, 51, 56, 73, 89])

In [34]:
arr = np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr = np.random.randint(0,50,10)

In [37]:
ranarr

array([17, 48, 33, 21, 41, 20, 40, 28, 14, 18])

In [39]:
# reshape methods returns an array with same data but of different shape
arr.reshape(5,5)      # 1-d to 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr.reshape(2,3)       
# while coverting 1-d to 2-d, the desired no.of.rows*no.of.columns should be equal to number of elements of initial arrat

ValueError: cannot reshape array of size 25 into shape (2,3)

In [42]:
ranarr.max()

48

In [43]:
ranarr.min()

14

In [44]:
ranarr

array([17, 48, 33, 21, 41, 20, 40, 28, 14, 18])

In [45]:
ranarr.argmax()
# returns the index position of the max value

1

In [46]:
ranarr.argmin()
# returns the index position of the min value

8

In [48]:
# to know the shape of the array
ranarr.shape

(10,)

In [50]:
arr.shape

(25,)

In [51]:
arr = arr.reshape(5,5)

In [52]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr.shape

(5, 5)

In [54]:
arr.dtype

dtype('int64')

In [56]:
# Instead of using np.random.randint(), we can do as below
from numpy.random import randint

In [57]:
randint(1,100)

68