In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [12]:
# Broadcast the values of array
arr[0:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr1 = np.arange(0,11)

In [16]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr1 = arr1[0:6]

In [18]:
slice_of_arr1

array([0, 1, 2, 3, 4, 5])

In [19]:
slice_of_arr1[:] = 99

In [20]:
slice_of_arr1

array([99, 99, 99, 99, 99, 99])

In [23]:
# change in original array too
arr1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
# Numpy doesn't automatically have copy of arrays, inorder to avoid memory issues.
# thus, though we change slice_of_arr1, the change will be reflected in it's original array arr1
# Therefore, if we want to copy an array
arr1_copy = arr1.copy()

In [27]:
arr1_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
arr1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr1_copy[:] = 100

In [30]:
arr1_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [31]:
arr1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [32]:
# without copying, the new variables will be only link to the original variables.
# If we change something in new variable, that will be reflected in original one

## Matrices -- 2-d Array

In [33]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [35]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
arr_2d[0][0]     # first row, first column element

5

In [38]:
arr_2d[0]       # first row

array([ 5, 10, 15])

In [39]:
arr_2d[1][1]

25

In [40]:
#To get digit 40
arr_2d[2][1]     # third row, second column

40

In [41]:
arr_2d[2,1]

40

In [42]:
#To get digit 30
arr_2d[1,2]

30

In [43]:
arr_2d[1][2]

30

In [44]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [45]:
arr_2d[:2,1:]         # all rows upto 2, all colums from 1 -- 2 and 1 or indexes  

array([[10, 15],
       [25, 30]])

In [46]:
arr_2d[:2,]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [50]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [51]:
arr = np.arange(1,11)

In [52]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr > 5    # False, if comparision is false and True, if comparision is true

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [55]:
bool_arr = arr > 5 

In [56]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [57]:
arr[bool_arr]      # elements of arr where bool_arr elements are true
# returns instances only where bool_arr values are true

array([ 6,  7,  8,  9, 10])

In [58]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [59]:
arr[arr<3]

array([1, 2])

In [60]:
arr_2d = np.arange(0,50)

In [61]:
arr_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [62]:
arr_2d = arr_2d.reshape(5,10)

In [63]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [64]:
arr_2d = np.arange(0,50).reshape(5,10)

In [65]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [68]:
# for elements 13, 14 and 23,24

arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [69]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [70]:
arr_2d[:,3:5]

array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34],
       [43, 44]])